@echo off
setlocal enabledelayedexpansion

SET OUTPUT_FILE=..\buildnumber.h

REM Get commit count
for /f "delims=" %%i in ('git rev-list HEAD --count') do set BUILD_NUMBER=%%i

REM Get short commit hash
for /f "delims=" %%i in ('git rev-parse --short HEAD') do set COMMIT_HASH=%%i

REM Get UTC time using PowerShell
powershell -command "$utc = (Get-Date).ToUniversalTime(); Write-Host $utc.ToString('yyyy-MM-dd HH:mm:ss UTC')" > "%TEMP%\utctime.txt"
set /p BUILD_TIME_UTC=<"%TEMP%\utctime.txt"
del "%TEMP%\utctime.txt"

echo Build Number: %BUILD_NUMBER%
echo Commit Hash: %COMMIT_HASH%
echo Build Time: %BUILD_TIME_UTC%

REM Create temporary file
(
    echo // Auto-generated by gitrev.cmd - DO NOT EDIT
    echo #ifndef BUILDNUMBER_H
    echo #define BUILDNUMBER_H
    echo.
    echo #define BUILD_NUMBER %BUILD_NUMBER%
    echo #define BUILD_NUMBER_STR "%BUILD_NUMBER%"
    echo #define COMMIT_HASH "%COMMIT_HASH%"
    echo #define BUILD_TIME_UTC "%BUILD_TIME_UTC%"
    echo #define BUILD_HOST "%COMPUTERNAME%"
    echo.
    echo #endif // BUILDNUMBER_H
) > "%OUTPUT_FILE%.tmp"

REM Only update if different
fc "%OUTPUT_FILE%.tmp" "%OUTPUT_FILE%" > nul 2>&1
if errorlevel 1 (
    move /y "%OUTPUT_FILE%.tmp" "%OUTPUT_FILE%"
    echo Generated %OUTPUT_FILE%
) else (
    del "%OUTPUT_FILE%.tmp"
    echo %OUTPUT_FILE% unchanged
)

endlocal
exit /b 0