// Auto-generated by gitrev.cmd - DO NOT EDIT
#ifndef BUILDNUMBER_H
#define BUILDNUMBER_H

#define BUILD_NUMBER 26
#define BUILD_NUMBER_STR "26"
#define COMMIT_HASH "7e1b963"
#define BUILD_TIME_UTC "2025-12-20 19:46:09 UTC"
#define BUILD_HOST "REDACTED"

#endif // BUILDNUMBER_H
